[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "package"
version = "0.0.1"
packages = [
    { include = "package", from = "src" },
]
description = "Python package description."
authors = [
    "Alvaro Bartolome <alvarobartt@yahoo.com>"
]
readme = "README.md"
homepage = "https://github.com/alvarobartt/python-package-template"
documentation = "https://github.com/alvarobartt/python-package-template"
repository = "https://github.com/alvarobartt/python-package-template"
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.931"
pre-commit = "^2.17.0"

[tool.isort]
profile = "black"

[tool.mypy]
# --strict
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
implicit_reexport = false
strict_equality = true
# --strict end